//! What never enters the shared tree.
//!
//! One filter, used by both the scanner and the watcher. They have to agree:
//! if the watcher lets `node_modules` through, a dependency install floods
//! every guest with churn the scanner never showed them in the first place.

use std::path::Path;

use anyhow::Result;
use ignore::gitignore::{Gitignore, GitignoreBuilder};

/// Directories that are generated by definition. Excluded whether or not the
/// project has a `.gitignore` — plenty don't, and those are exactly the
/// projects that would otherwise share 40,000 files of dependencies.
pub const ALWAYS_SKIP: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    ".next",
    ".nuxt",
    ".svelte-kit",
    "__pycache__",
    ".venv",
    "venv",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".gradle",
    ".tox",
    ".turbo",
    ".parcel-cache",
    "DerivedData",
    ".DS_Store",
];

pub struct Filter {
    root: std::path::PathBuf,
    gitignore: Gitignore,
}

impl Filter {
    /// Builds from the project's own `.gitignore`, if it has one.
    pub fn build(root: &Path) -> Result<Self> {
        let mut b = GitignoreBuilder::new(root);
        // Errors here are per-line parse complaints; a malformed ignore file
        // should not stop someone sharing their work.
        let _ = b.add(root.join(".gitignore"));
        let _ = b.add(root.join(".ignore"));
        Ok(Self {
            root: root.to_path_buf(),
            gitignore: b.build()?,
        })
    }

    /// True when this path should never reach a guest.
    pub fn is_ignored(&self, path: &Path, is_dir: bool) -> bool {
        let Ok(rel) = path.strip_prefix(&self.root) else {
            // Outside the workspace entirely. Nothing to discuss.
            return true;
        };
        if rel.as_os_str().is_empty() {
            return false;
        }
        if rel
            .components()
            .any(|c| ALWAYS_SKIP.contains(&c.as_os_str().to_string_lossy().as_ref()))
        {
            return true;
        }
        self.gitignore
            .matched_path_or_any_parents(rel, is_dir)
            .is_ignore()
    }

    /// Relative, forward-slashed path for the wire, or `None` if the path is
    /// outside the workspace.
    pub fn relative(&self, path: &Path) -> Option<String> {
        let rel = path.strip_prefix(&self.root).ok()?;
        if rel.as_os_str().is_empty() {
            return None;
        }
        Some(
            rel.components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/"),
        )
    }

    /// Resolve a wire path back to disk, refusing anything that escapes the
    /// workspace. `..` in a path from a guest is not a mistake to be lenient
    /// about.
    pub fn resolve(&self, rel: &str) -> Option<std::path::PathBuf> {
        if rel.is_empty() || rel.starts_with('/') {
            return None;
        }
        let mut out = self.root.clone();
        for part in rel.split('/') {
            if part.is_empty() || part == "." || part == ".." {
                return None;
            }
            out.push(part);
        }
        // A symlink pointing outside the workspace is an escape hatch we do
        // not want, so compare the canonical form too.
        let canonical = out.canonicalize().ok()?;
        let root = self.root.canonicalize().ok()?;
        canonical.starts_with(&root).then_some(canonical)
    }

    pub fn root(&self) -> &Path {
        &self.root
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn scratch(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("ajar-filter-{name}"));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir.canonicalize().unwrap()
    }

    #[test]
    fn skips_generated_directories_without_any_gitignore() {
        let root = scratch("generated");
        let f = Filter::build(&root).unwrap();
        assert!(f.is_ignored(&root.join("node_modules"), true));
        assert!(f.is_ignored(&root.join("node_modules/react/index.js"), false));
        assert!(f.is_ignored(&root.join(".git/HEAD"), false));
        assert!(f.is_ignored(&root.join("target/debug/thing"), false));
        assert!(!f.is_ignored(&root.join("src/main.rs"), false));
    }

    #[test]
    fn honours_the_projects_own_gitignore() {
        let root = scratch("gitignore");
        fs::write(root.join(".gitignore"), "secrets/\n*.log\n").unwrap();
        let f = Filter::build(&root).unwrap();
        assert!(f.is_ignored(&root.join("secrets"), true));
        assert!(f.is_ignored(&root.join("secrets/key.pem"), false));
        assert!(f.is_ignored(&root.join("debug.log"), false));
        assert!(!f.is_ignored(&root.join("README.md"), false));
    }

    #[test]
    fn dotfiles_are_visible_unless_ignored() {
        let root = scratch("dotfiles");
        let f = Filter::build(&root).unwrap();
        // A shared project usually wants .gitignore and .editorconfig shown.
        assert!(!f.is_ignored(&root.join(".gitignore"), false));
        assert!(!f.is_ignored(&root.join(".editorconfig"), false));
    }

    #[test]
    fn refuses_paths_that_escape_the_workspace() {
        let root = scratch("escape");
        fs::write(root.join("ok.txt"), "hi").unwrap();
        let f = Filter::build(&root).unwrap();

        assert!(f.resolve("ok.txt").is_some());
        assert!(f.resolve("../etc/passwd").is_none());
        assert!(f.resolve("a/../../b").is_none());
        assert!(f.resolve("/etc/passwd").is_none());
        assert!(f.resolve("").is_none());
    }

    #[test]
    fn refuses_a_symlink_that_points_outside() {
        let root = scratch("symlink");
        let outside = scratch("symlink-target");
        fs::write(outside.join("secret.txt"), "nope").unwrap();
        #[cfg(unix)]
        std::os::unix::fs::symlink(&outside, root.join("escape")).unwrap();

        let f = Filter::build(&root).unwrap();
        #[cfg(unix)]
        assert!(
            f.resolve("escape/secret.txt").is_none(),
            "a symlink out of the workspace should not resolve"
        );
    }

    #[test]
    fn relative_paths_use_forward_slashes() {
        let root = scratch("relative");
        let f = Filter::build(&root).unwrap();
        assert_eq!(
            f.relative(&root.join("src").join("main.rs")).as_deref(),
            Some("src/main.rs")
        );
        assert_eq!(f.relative(&root), None);
        assert_eq!(f.relative(Path::new("/somewhere/else")), None);
    }
}
