//! What never enters the shared tree.
//!
//! One filter, used by both the scanner and the watcher. They have to agree:
//! if the watcher lets `node_modules` through, a dependency install floods
//! every guest with churn the scanner never showed them in the first place.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use anyhow::Result;
use ignore::gitignore::{Gitignore, GitignoreBuilder};
use ignore::Match;

/// Directories that are generated by definition. Excluded whether or not the
/// project has a `.gitignore` — plenty don't, and those are exactly the
/// projects that would otherwise share 40,000 files of dependencies.
pub const ALWAYS_SKIP: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    ".next",
    ".nuxt",
    ".svelte-kit",
    "__pycache__",
    ".venv",
    "venv",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".gradle",
    ".tox",
    ".turbo",
    ".parcel-cache",
    "DerivedData",
    ".DS_Store",
];

/// The ignore files a directory can hold, the one that wins first.
const IGNORE_FILES: [&str; 2] = [".ignore", ".gitignore"];

pub struct Filter {
    root: std::path::PathBuf,
    /// Everything that is not in the shared folder itself, weakest last: the
    /// ignore files above it up to the repository's top, the repository's
    /// `info/exclude`, and git's global excludes. Read once.
    outer: Vec<Gitignore>,
    /// Each directory's own ignore files, read the first time a path under it
    /// is asked about and forgotten when one of them changes.
    nested: Mutex<HashMap<PathBuf, Arc<Vec<Gitignore>>>>,
}

/// One directory's ignore files, strongest first. Errors are per-line parse
/// complaints; a malformed ignore file should not stop someone sharing.
fn read_dir_rules(dir: &Path) -> Vec<Gitignore> {
    IGNORE_FILES
        .iter()
        .map(|name| dir.join(name))
        .filter(|file| file.is_file())
        .filter_map(|file| {
            let mut b = GitignoreBuilder::new(dir);
            let _ = b.add(file);
            b.build().ok()
        })
        .collect()
}

impl Filter {
    /// The same rules the scanner's walk applies, so the watcher agrees with
    /// it. It used to read only the root's `.gitignore` and `.ignore`, while
    /// the walk honoured nested ones, `info/exclude` and the global excludes
    /// too — so a change under, say, a `sub/build/` that only a nested file
    /// excluded reached every guest until the next resync.
    pub fn build(root: &Path) -> Result<Self> {
        let mut outer = Vec::new();
        // Above the shared folder, up to the repository it sits in, if any.
        let top = root.ancestors().find(|d| d.join(".git").exists());
        if let Some(top) = top {
            for dir in root.ancestors().skip(1) {
                if !dir.starts_with(top) {
                    break;
                }
                outer.extend(read_dir_rules(dir));
            }
            let exclude = top.join(".git").join("info").join("exclude");
            if exclude.is_file() {
                let mut b = GitignoreBuilder::new(top);
                let _ = b.add(exclude);
                outer.extend(b.build().ok());
            }
        }
        let (global, _) = Gitignore::global();
        outer.push(global);
        Ok(Self {
            root: root.to_path_buf(),
            outer,
            nested: Mutex::new(HashMap::new()),
        })
    }

    fn rules_in(&self, dir: &Path) -> Arc<Vec<Gitignore>> {
        let mut nested = self.nested.lock().unwrap_or_else(|e| e.into_inner());
        nested
            .entry(dir.to_path_buf())
            .or_insert_with(|| Arc::new(read_dir_rules(dir)))
            .clone()
    }

    /// An ignore file changed, so its directory's rules are read again on the
    /// next question rather than answered from what it said before.
    pub fn changed(&self, path: &Path) {
        let is_rules = path
            .file_name()
            .is_some_and(|n| IGNORE_FILES.iter().any(|f| n == *f));
        if let (true, Some(dir)) = (is_rules, path.parent()) {
            self.nested
                .lock()
                .unwrap_or_else(|e| e.into_inner())
                .remove(dir);
        }
    }

    /// True when this path should never reach a guest.
    pub fn is_ignored(&self, path: &Path, is_dir: bool) -> bool {
        let Ok(rel) = path.strip_prefix(&self.root) else {
            // Outside the workspace entirely. Nothing to discuss.
            return true;
        };
        if rel.as_os_str().is_empty() {
            return false;
        }
        if rel
            .components()
            .any(|c| ALWAYS_SKIP.contains(&c.as_os_str().to_string_lossy().as_ref()))
        {
            return true;
        }
        // The deepest directory's rules first: a nested file overrides one
        // above it, as git has it. The first rule that says anything decides.
        let decide = |rules: &[Gitignore]| -> Option<bool> {
            rules
                .iter()
                .find_map(|g| match g.matched_path_or_any_parents(path, is_dir) {
                    Match::None => None,
                    m => Some(m.is_ignore()),
                })
        };
        for dir in path.ancestors().skip(1) {
            if !dir.starts_with(&self.root) {
                break;
            }
            if let Some(ignored) = decide(&self.rules_in(dir)) {
                return ignored;
            }
        }
        decide(&self.outer).unwrap_or(false)
    }

    /// Relative, forward-slashed path for the wire, or `None` if the path is
    /// outside the workspace.
    pub fn relative(&self, path: &Path) -> Option<String> {
        let rel = path.strip_prefix(&self.root).ok()?;
        if rel.as_os_str().is_empty() {
            return None;
        }
        Some(
            rel.components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/"),
        )
    }

    /// Resolve a wire path back to disk, refusing anything that escapes the
    /// workspace. `..` in a path from a guest is not a mistake to be lenient
    /// about.
    pub fn resolve(&self, rel: &str) -> Option<std::path::PathBuf> {
        if rel.is_empty() || rel.starts_with('/') {
            return None;
        }
        let mut out = self.root.clone();
        for part in rel.split('/') {
            if part.is_empty() || part == "." || part == ".." {
                return None;
            }
            out.push(part);
        }
        // A symlink pointing outside the workspace is an escape hatch we do
        // not want, so compare the canonical form too.
        let canonical = out.canonicalize().ok()?;
        let root = self.root.canonicalize().ok()?;
        canonical.starts_with(&root).then_some(canonical)
    }

    /// `resolve`, and also refused when the path — as written, or where it
    /// leads — is one the tree never shows: `.git`, dependencies, anything
    /// the ignore files name. A read asked for by path used to skip that
    /// question, so a guest could fetch `.git/config` or a gitignored `.env`
    /// by name, read-only guests too, who have no terminal to do it with.
    pub fn resolve_shared(&self, rel: &str) -> Option<std::path::PathBuf> {
        let canonical = self.resolve(rel)?;
        if self.is_ignored(&self.root.join(rel), false) {
            return None;
        }
        // Where it leads, measured against the root's canonical form, then
        // asked about in the root's own spelling: `is_ignored` compares with
        // `root` as given, and on a Mac a temp directory canonicalises from
        // /var to /private/var.
        let inside = canonical
            .strip_prefix(self.root.canonicalize().ok()?)
            .ok()?;
        if self.is_ignored(&self.root.join(inside), false) {
            return None;
        }
        Some(canonical)
    }

    pub fn root(&self) -> &Path {
        &self.root
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn scratch(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("ajar-filter-{name}"));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir.canonicalize().unwrap()
    }

    #[test]
    fn skips_generated_directories_without_any_gitignore() {
        let root = scratch("generated");
        let f = Filter::build(&root).unwrap();
        assert!(f.is_ignored(&root.join("node_modules"), true));
        assert!(f.is_ignored(&root.join("node_modules/react/index.js"), false));
        assert!(f.is_ignored(&root.join(".git/HEAD"), false));
        assert!(f.is_ignored(&root.join("target/debug/thing"), false));
        assert!(!f.is_ignored(&root.join("src/main.rs"), false));
    }

    #[test]
    fn honours_the_projects_own_gitignore() {
        let root = scratch("gitignore");
        fs::write(root.join(".gitignore"), "secrets/\n*.log\n").unwrap();
        let f = Filter::build(&root).unwrap();
        assert!(f.is_ignored(&root.join("secrets"), true));
        assert!(f.is_ignored(&root.join("secrets/key.pem"), false));
        assert!(f.is_ignored(&root.join("debug.log"), false));
        assert!(!f.is_ignored(&root.join("README.md"), false));
    }

    #[test]
    fn honours_a_nested_gitignore() {
        // The scanner's walk always did; the watcher read only the root's.
        let root = scratch("nested");
        fs::create_dir_all(root.join("sub")).unwrap();
        fs::write(root.join("sub/.gitignore"), "out/\n*.tmp\n").unwrap();
        let f = Filter::build(&root).unwrap();
        assert!(f.is_ignored(&root.join("sub/out/a.txt"), false));
        assert!(f.is_ignored(&root.join("sub/x.tmp"), false));
        assert!(
            !f.is_ignored(&root.join("x.tmp"), false),
            "a nested file reaches only below itself"
        );
        assert!(!f.is_ignored(&root.join("sub/keep.txt"), false));
    }

    #[test]
    fn a_nested_file_overrides_the_one_above() {
        let root = scratch("override");
        fs::create_dir_all(root.join("sub")).unwrap();
        fs::write(root.join(".gitignore"), "*.log\n").unwrap();
        fs::write(root.join("sub/.gitignore"), "!keep.log\n").unwrap();
        let f = Filter::build(&root).unwrap();
        assert!(f.is_ignored(&root.join("a.log"), false));
        assert!(!f.is_ignored(&root.join("sub/keep.log"), false));
        assert!(f.is_ignored(&root.join("sub/other.log"), false));
    }

    #[test]
    fn honours_the_repositorys_info_exclude() {
        let root = scratch("exclude");
        fs::create_dir_all(root.join(".git/info")).unwrap();
        fs::write(root.join(".git/info/exclude"), "private.txt\n").unwrap();
        let f = Filter::build(&root).unwrap();
        assert!(f.is_ignored(&root.join("private.txt"), false));
        assert!(!f.is_ignored(&root.join("public.txt"), false));
    }

    #[test]
    fn an_edited_ignore_file_is_read_again() {
        let root = scratch("edited");
        fs::create_dir_all(root.join("sub")).unwrap();
        let f = Filter::build(&root).unwrap();
        assert!(!f.is_ignored(&root.join("sub/new.tmp"), false));
        fs::write(root.join("sub/.gitignore"), "*.tmp\n").unwrap();
        f.changed(&root.join("sub/.gitignore"));
        assert!(f.is_ignored(&root.join("sub/new.tmp"), false));
    }

    #[test]
    fn dotfiles_are_visible_unless_ignored() {
        let root = scratch("dotfiles");
        let f = Filter::build(&root).unwrap();
        // A shared project usually wants .gitignore and .editorconfig shown.
        assert!(!f.is_ignored(&root.join(".gitignore"), false));
        assert!(!f.is_ignored(&root.join(".editorconfig"), false));
    }

    #[test]
    fn refuses_paths_that_escape_the_workspace() {
        let root = scratch("escape");
        fs::write(root.join("ok.txt"), "hi").unwrap();
        let f = Filter::build(&root).unwrap();

        assert!(f.resolve("ok.txt").is_some());
        assert!(f.resolve("../etc/passwd").is_none());
        assert!(f.resolve("a/../../b").is_none());
        assert!(f.resolve("/etc/passwd").is_none());
        assert!(f.resolve("").is_none());
    }

    #[test]
    fn refuses_a_symlink_that_points_outside() {
        let root = scratch("symlink");
        let outside = scratch("symlink-target");
        fs::write(outside.join("secret.txt"), "nope").unwrap();
        #[cfg(unix)]
        std::os::unix::fs::symlink(&outside, root.join("escape")).unwrap();

        let f = Filter::build(&root).unwrap();
        #[cfg(unix)]
        assert!(
            f.resolve("escape/secret.txt").is_none(),
            "a symlink out of the workspace should not resolve"
        );
    }

    #[test]
    fn relative_paths_use_forward_slashes() {
        let root = scratch("relative");
        let f = Filter::build(&root).unwrap();
        assert_eq!(
            f.relative(&root.join("src").join("main.rs")).as_deref(),
            Some("src/main.rs")
        );
        assert_eq!(f.relative(&root), None);
        assert_eq!(f.relative(Path::new("/somewhere/else")), None);
    }
}
